<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Learning Suite" duration-ms="4305" started-at="2019-11-28T18:32:55Z" finished-at="2019-11-28T18:33:00Z">
    <groups>
    </groups>
    <test name="First test" duration-ms="4305" started-at="2019-11-28T18:32:55Z" finished-at="2019-11-28T18:33:00Z">
      <class name="com.testcases.GetAPI">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.testcases.GetAPI@59f99ea]" name="setup" is-config="true" duration-ms="44" started-at="2019-11-28T18:32:56Z" finished-at="2019-11-28T18:32:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getAPI()[pri:0, instance:com.testcases.GetAPI@59f99ea]" name="getAPI" duration-ms="3235" started-at="2019-11-28T18:32:56Z" finished-at="2019-11-28T18:32:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAPI -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.testcases.GetAPI@59f99ea]" name="teardown" is-config="true" duration-ms="0" started-at="2019-11-28T18:32:59Z" finished-at="2019-11-28T18:32:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.testcases.GetAPI -->
      <class name="com.testcases.PostTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.testcases.PostTest@27efef64]" name="setup" is-config="true" duration-ms="2" started-at="2019-11-28T18:32:59Z" finished-at="2019-11-28T18:32:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="PostAPI()[pri:1, instance:com.testcases.PostTest@27efef64]" name="PostAPI" duration-ms="779" started-at="2019-11-28T18:32:59Z" finished-at="2019-11-28T18:33:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.testcases.PostTest.PostAPI(PostTest.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostAPI -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.testcases.PostTest@27efef64]" name="teardown" is-config="true" duration-ms="0" started-at="2019-11-28T18:33:00Z" finished-at="2019-11-28T18:33:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.testcases.PostTest -->
    </test> <!-- First test -->
  </suite> <!-- Learning Suite -->
</testng-results>
